const characters = [
  {name:"균균 밈이", grade:"일반", chance:0.001, color:"#bbb", desc:"평범한 밈 캐릭터"},
  {name:"짱균", grade:"일반", chance:0.001, color:"#bbb", desc:"힘이 센 균균"},
  {name:"귀염균", grade:"일반", chance:0.001, color:"#bbb", desc:"귀여운 균균"},
  {name:"스마일균", grade:"일반", chance:0.001, color:"#bbb", desc:"항상 웃는 균균"},
  {name:"학교 앞 분식집 균", grade:"일반", chance:0.001, color:"#bbb", desc:"학교 앞 분식집을 지키는 균"},
  {name:"동네 슈퍼 균", grade:"일반", chance:0.001, color:"#ccc", desc:"동네 슈퍼에서 항상 만나는 균"},
  {name:"학원 출석왕 균", grade:"일반", chance:0.001, color:"#ddd", desc:"학원 출석률 100%의 전설"},
  {name:"PC방 마스터 균", grade:"일반", chance:0.001, color:"#eee", desc:"PC방에서 살아가는 균"},
  {name:"공원 산책 균", grade:"일반", chance:0.001, color:"#aaa", desc:"공원을 느긋하게 걷는 균"},
  {name:"도서관 사서 균", grade:"일반", chance:0.001, color:"#bbb", desc:"책을 사랑하는 조용한 균"},
  {name:"자전거 여행 균", grade:"일반", chance:0.001, color:"#ccc", desc:"자전거로 세상을 여행하는 균"},
  {name:"음악 감상 균", grade:"일반", chance:0.001, color:"#ddd", desc:"이어폰을 항상 끼고 있는 균"},
  {name:"만화책 탐닉 균", grade:"일반", chance:0.001, color:"#eee", desc:"만화책에 빠진 균"},
  {name:"길거리 포켓몬 균", grade:"일반", chance:0.001, color:"#aaa", desc:"길거리에서 포켓몬을 찾는 균"},

  {name:"피카균", grade:"희귀", chance:0.0005, color:"#4af", desc:"전기를 다루는 균"},
  {name:"불균", grade:"희귀", chance:0.0005, color:"#4af", desc:"불꽃을 사용하는 균"},
  {name:"게임 폐인 균", grade:"희귀", chance:0.0005, color:"#4af", desc:"게임만 하는 전설적인 균"},
  {name:"밤샘 코딩 균", grade:"희귀", chance:0.0005, color:"#5af", desc:"밤새 코딩하는 개발자 균"},
  {name:"리플레이왕 균", grade:"희귀", chance:0.0005, color:"#6af", desc:"게임 리플레이 분석 마스터"},
  {name:"마라톤 균", grade:"희귀", chance:0.0005, color:"#7af", desc:"끝없이 달리는 체력왕 균"},
  {name:"도전왕 균", grade:"희귀", chance:0.0005, color:"#8af", desc:"모든 도전을 즐기는 균"},
  {name:"퍼즐 마스터 균", grade:"희귀", chance:0.0005, color:"#9af", desc:"퍼즐을 완벽하게 푸는 균"},
  {name:"낚시광 균", grade:"희귀", chance:0.0005, color:"#aaf", desc:"낚시에 미쳐있는 균"},
  {name:"요리사 균", grade:"희귀", chance:0.0005, color:"#baf", desc:"요리를 잘하는 균"},

  {name:"얼음균", grade:"초희귀", chance:0.0003, color:"#7ff", desc:"얼음으로 공격하는 균"},
  {name:"바람균", grade:"초희귀", chance:0.0003, color:"#7ff", desc:"바람을 다루는 균"},

  {name:"갓균", grade:"에픽", chance:0.0002, color:"#a4f", desc:"밈의 신"},
  {name:"초균", grade:"에픽", chance:0.0002, color:"#a4f", desc:"초능력을 가진 균"},
  {name:"번개의 투사 균", grade:"에픽", chance:0.0002, color:"#a4f", desc:"번개의 힘을 사용하는 균"},
  {name:"스텔스 균", grade:"에픽", chance:0.0002, color:"#b4f", desc:"그림자 속에 숨는 균"},
  {name:"불타는 심장 균", grade:"에픽", chance:0.0002, color:"#c4f", desc:"열정이 넘치는 불꽃 균"},
  {name:"얼음의 기사 균", grade:"에픽", chance:0.0002, color:"#d4f", desc:"차가운 얼음 갑옷의 기사균"},
  {name:"그림자 균", grade:"에픽", chance:0.0002, color:"#e4f", desc:"어둠 속에서 움직이는 균"},

  {name:"미라클균", grade:"신화", chance:0.0001, color:"#ff6", desc:"기적을 부르는 균"},
  {name:"신성균", grade:"신화", chance:0.0001, color:"#ff6", desc:"신성한 힘을 가진 균"},

  {name:"균균 황제", grade:"전설", chance:0.00005, color:"#fb0", desc:"최강의 균 황제"},
  {name:"암흑균", grade:"전설", chance:0.00005, color:"#fb0", desc:"어둠 속에서 힘을 키운 균"},
  {name:"불멸균", grade:"전설", chance:0.00005, color:"#fb0", desc:"죽지 않는 불멸의 균"},
  {name:"천둥균", grade:"전설", chance:0.00005, color:"#fb0", desc:"번개를 다루는 전설의 균"},
  {name:"용균", grade:"전설", chance:0.00005, color:"#fb0", desc:"용의 힘을 가진 균"},
  {name:"시간을 달리는 균", grade:"전설", chance:0.00005, color:"#fb0", desc:"시간을 넘어 달리는 균"},
  {name:"천둥의 손 균", grade:"전설", chance:0.00005, color:"#fc0", desc:"번개를 손에 쥔 균"},
  {name:"용암 균", grade:"전설", chance:0.00005, color:"#fd0", desc:"용암의 힘을 가진 균"},
  {name:"별빛 균", grade:"전설", chance:0.00005, color:"#fe0", desc:"별빛을 다루는 균"},

  {name:"카오스균", grade:"초월", chance:0.00002, color:"#f0f", desc:"혼돈을 부르는 균"},
  {name:"시간의 지배자균", grade:"초월", chance:0.00002, color:"#f0f", desc:"시간을 지배하는 균"},
  {name:"초월균", grade:"초월", chance:0.00002, color:"#f0f", desc:"차원을 초월한 균"},
  {name:"무한균", grade:"초월", chance:0.00002, color:"#f0f", desc:"무한한 힘을 가진 균"},

  {name:"𝒜𝒷𝓎𝓈𝓈𝒶𝓁 𝐺𝓎𝓊𝓃", grade:"시크릿", chance:0.0000000000000000001, color:"#0a1f44", desc:"심연에서 태어난 균"},
  {name:"ℒ𝑜𝓇𝒹 𝑜𝒻 𝓉𝒽𝑒 𝐷𝑒𝓅𝓉𝒽𝓈 𝒢𝓎𝓊𝓃", grade:"시크릿", chance:0.00000000000000000000000000000000001, color:"#2e004f", desc:"심해를 지배하는 균의 군주"}
];
